---
id: sapporoonga-20140329
base_name: how-to-start-droonga
tags:
- rabbit
- groonga
- droonga
- sapporoonga
presentation_date: 2014-03-29
version: 2014.3.29.0
licenses:
- CC BY-SA 3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
